Repository Skhuthon/Skhuthon_0th_TEAM09_FE, pull requests merged in 2024-06, with the labels that each got.

#3 #2 기초세팅 마무리
  .github/ISSUE_TEMPLATE/기능-추가.md
  .github/ISSUE_TEMPLATE/버그-발생.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 복제

#8 Develop#4
  public/login/googlelogin.png
  public/login/kakaologin.png
  src/pages/login.tsx
  src/pages/user/login.tsx
Labels: 병합

#10 #5 메인화면 디자인
  package.json
  public/images/canon.jpg
  public/images/cha.jpg
  public/images/data_science.jpg
  public/images/monitor.jpg
  public/images/sunjea.webp
  public/images/tablet.jpg
  src/components/Footer.tsx
  src/components/index/login_alram_modal.tsx
  src/components/navbar.tsx
  src/components/sidebar.tsx
  src/components/wirte/delete_modal.tsx
  src/pages/index.tsx
  src/styles/globals.css
  yarn.lock
Labels: 병합

#14 #11 수정이 안되었던 부분 수정
  src/pages/index.tsx
Labels: 병합

#15 개발을 위한 병합
  package-lock.json
  src/components/Footer.tsx
  src/components/navbar.tsx
  src/components/wirte/delete_modal.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  yarn.lock
Labels: 병합

#19 Develop#13
  public/main/mainlogo.png
  src/components/main/categorization.tsx
  src/components/main/category.tsx
  src/components/main/iteam.tsx
  src/components/navbar.tsx
  src/pages/api/board.ts
  src/pages/api/categories.ts
  src/pages/api/categorization.ts
  src/pages/index.tsx
  src/pages/main.tsx
Labels: 병합

#20 마이페이지 전반적 수정
  public/main/mainlogo.png
  src/components/main/categorization.tsx
  src/components/main/category.tsx
  src/components/main/iteam.tsx
  src/components/navbar.tsx
  src/components/wirte/delete_modal.tsx
  src/pages/api/board.ts
  src/pages/api/categories.ts
  src/pages/api/categorization.ts
  src/pages/index.tsx
  src/pages/main.tsx
Labels: 버그, 문제 발생

#21 Develop#6
  src/components/mypage/bookmarklist.tsx
  src/components/mypage/likelist.tsx
  src/components/mypage/mypageinfo.tsx
  src/components/mypage/mypagelist.tsx
  src/components/mypage/mypost.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/api/bookmarklist.ts
  src/pages/mypage.tsx
  src/pages/mypage/bookmarklist.tsx
  src/pages/mypage/likelist.tsx
  src/pages/mypage/mypageinfo.tsx
  src/pages/mypage/mypost.tsx
  src/styles/globals.css
Labels: 버그, 개발, 수정 금지
